encoder_params:
  image_size: 256
  patch_size: 8
  hidden_dim: 768
  num_layers: 12
  num_heads: 12
  mlp_dim: 3072

decoder_params:
  image_size: 256
  patch_size: 8
  hidden_dim: 768
  num_layers: 12
  num_heads: 12
  mlp_dim: 3072

quantizer_params:
  codebook_dim: 32
  codebook_size: 8192

loss_params:
  stylegan_size: 256
  loglaplace_weight: 0.0
  loggaussian_weight: 1.0
  perceptual_weight: 0.1
  adversarial_weight: 0.1

data_params:
  name: "imagenet"
  root_path: "./data/imagenet"
  batch_size: 4
  num_workers: 8

training_params:
  report_to_wandb: True
  gradient_accumulation_steps: 2
  log_steps: 100
  eval_steps: 500
  save_every: 5000
  save_dir: ".logs"
