encoder_params:
  image_size: 256
  patch_size: 8
  hidden_dim: 512
  num_layers: 8
  num_heads: 8
  mlp_dim: 2048
decoder_params:
  image_size: 256
  patch_size: 8
  hidden_dim: 512
  num_layers: 8
  num_heads: 8
  mlp_dim: 2048
quantizer_params:
  codebook_dim: 32
  codebook_size: 8192
loss_params:
  stylegan_size: 256
  loglaplace_weight: 0.0
  loggaussian_weight: 1.0
  perceptual_weight: 0.1
  adversarial_weight: 0.1
